### ISSUE TITLE
컴파일 옵션 `-mthumb-interwork`은 반드시 필요한가요?

### ISSUE THREAD

**Issue by bongjunj** [navilera/Navilos#10]
71쪽에 `CLAGS`에 지정된 컴파일 옵션은 `-c -g -std=c11` 인데,
93쪽에서는 딸린 설명없이 `mthumb-interwork`가 추가됩니다.

이 컴파일 옵션이 없어도 navilos가 잘 실행되는데요, 반드시 필요한 옵션인가요?

**Comment by navilera** [comment]
`mthumb-interwork`는 ARM 모드 인스트럭션하고 thumb 모드 인스트럭션이 서로 call 할 때 이를 처리해주는 코드를 컴파일러가 만들어 주는 옵션입니다.
아마 책에 넣을 어떤 기능을 테스트하려고 넣어두고 서는 책에 넣기에 너무 어렵거나 혹은 책에 넣을 만큼 꼭 필요한 내용이 아니라서 책에 코드 설명은 안하고 Makefile은 수정을 안한채로 원고를 작성했나봅니다.
책의 내용만 실습할 것이면 없어도 되는 옵션입니다.
만약 나빌로스에 다른 서드파티 코드를 붙여 무엇을 만들고, 해당 서드파티 코드가 thumb 모드로 빌드된다면 필요한 옵션입니다.
질문감사합니다.
