### ISSUE TITLE
3장 첫 Makefile에서 arm-none-eabi-gdb 문제 (ubuntu)

### ISSUE THREAD

**Issue by pjueon** [navilera/Navilos#11]
https://github.com/navilera/Navilos/blob/be7a34cce4553adba6c9bf6cdd2cdb709368df99/Makefile#L30-L31

ubuntu 22.04 LTS 환경에서 테스트 해보니 위 코드의 `arm-none-eabi-gdb` 를 찾을 수 없다고 에러가 발생합니다. 
설치해보려고 `sudo apt-get install arm-none-eabi-gdb`을 시도해봤으나 찾지 못하네요. 

대안으로 책 p25에 나와있는 `gdb-multiarch`를 사용하도록 아래와 같이 수정하면 정상 동작합니다.

```
gdb:
	gdb-multiarch $(navilos)
```

**Comment by navilera** [comment]
2쇄에서 책 내용은 수정했는데 여기 있는 코드는 수정을 안했군요.
PR 보내주시면 머지하겠습니다.

**Comment by pjueon** [comment]
넵 PR 작성하였습니다
