### ISSUE TITLE
(gdb) target remote:1234 에서 진행이 안됩니다!

### ISSUE THREAD

**Issue by gwanghwiseo** [navilera/Navilos#2]
리눅스 버전 : Ubuntu 20.04.1 LTS

<img width="458" alt="캡처" src="https://user-images.githubusercontent.com/33686685/94658834-568f0000-033e-11eb-99a4-3fa2df085495.PNG">

target remote:1234 를 입력해도 연결시간이 지났다고 떠서 교재 앞으로 진행이 안됩니다 ㅠㅠ 구글링을 계속 해봐도 해답이 안나와서 올려봅니다!

**Comment by navilera** [comment]
qemu가 떠 있는 상태에서 gdb를 실행해야 합니다.

**Comment by duty7351** [comment]
안녕하세요 저자님 qemu가 떠있는 상태면 (gdb) 프롬프트가 안나오는데 백그라운드 실행을 해야하나요?

**Comment by gwanghwiseo** [comment]
감사합니다 qemu실행 후 새로운 터미널로 gdb 실행해서 해결했습니다!
