### ISSUE TITLE
[오탈자] 현재까지 발견한 것

### ISSUE THREAD

**Issue by DonghoonPark12** [navilera/Navilos#3]
p.136
코드8.1 task.c --> task.h

p.148 
if(pNextTcb != pNextTcb) 맞나요??
if(pNextTcb != sCurrent_tcb) 아닌가요?

p.240
Line 9. FIQ --> NMFI 

책 잘보고 있습니다 :)

**Comment by DonghunP** [comment]
kernel/task.c 파일은 git이 책 내용이 조금 다릅니다. git 내용을 기반으로 이해하면 될까요?

**Comment by navilera** [comment]
네 맞습니다.
오탈자는 출판사에 전달하겠습니다.
