### ISSUE TITLE
#ARM_MODE_BIT_SVC와 =ARM_MODE_BIT_SVC의 차이점

### ISSUE THREAD

**Issue by ThereIsNoWindBag** [navilera/Navilos#5]
코드 4.4를 보면
```
reset_handler:
    MRS r0, cpsr
    BIC r1, r0, #0x1F
    ORR r1, r1, #ARM_MODE_BIT_SVC
    MSR cpsr, r1
    LDR sp, =SVC_STACK_TOP
```
같은 코드가 있습니다. 

둘 다 똑같이 C 헤더에서 #define으로 선언한 상수인데 왜 ORR에서는 #을 쓰고 LDR에서는 =을 쓰나요?
호환이 되는지 실험해 봤는데 서로 호환이 안되네요.

**Comment by navilera** [comment]
그냥 LDR 문법이 그렇습니다...

https://developer.arm.com/documentation/dui0473/m/writing-arm-assembly-language/load-addresses-to-a-register-using-ldr-rd---label
