### ISSUE TITLE
stm32 header 관련 문의

### ISSUE THREAD

**Issue by nshshk** [navilera/Navilos#9]
안녕하세요 stm32 소스를 추가 하신거 같아서 재밌게 잘 보고 있습니다.
감사합니다.

다만 지금 ubuntu에서 stm32f1xx_hal.h 헤더를 찾을 수 없다고 나오는데 패키지 설치가 필요한가요?

**Comment by navilera** [comment]
https://github.com/navilera/Gosu
여기에 stm32 + 나빌로스 작업한 빌드 되는 코드가 있습니다.
나빌로스에 stm32를 넣어 둔것은 나중에 작업하려고 일단 코드만 넣어둔 것인데... 몇 년째 안하고 있네요....
